services:
  ui:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    volumes:
      - ./data:/app/data