services:
  training_ui:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: ["uv", "run", "streamlit", "run", "app/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models

  live_ui:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: ["uv", "run", "streamlit", "run", "app/live_analysis.py", "--server.port=8502", "--server.address=0.0.0.0"]
    ports:
      - "8502:8502"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
