FROM python:3.10-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY common/ ./common
COPY worker/ ./worker

CMD ["uv", "run", "python", "worker/main.py"]
